### ISSUE TITLE
Support disabling GitHub stars check

### ISSUE THREAD

**Issue by repi** [mimoo/cargo-dephell#1]
When just running the tool on the command-line with only specifying `--manifest-path` and `-o` it still seems to do the GitHub stars check which caused it to fail for me on most crates with this:

```sh
text: Ok("{\"message\":\"API rate limit exceeded for aaa.bbb.ccc.ddd. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}\n")
dephell: crates.io request failed
status: 403 Forbidden
```

I hadn't set up a personal access token or specified it yet, maybe change to not do the stars check if `--github-token` is not specified?

**Comment by mimoo** [comment]
good point, just did this!

**Comment by mimoo** [comment]
(haven't tested it, tell me if it doesn't work)

**Comment by repi** [comment]
Thanks!
