### ISSUE TITLE
Running cargo-dephell on Firefox (mozilla-central) on Mac fails trying to compile windows-specific crates

### ISSUE THREAD

**Issue by bholley** [mimoo/cargo-dephell#9]
I'd love to run cargo-dephell against Firefox, but have hit some issues. STR:

```
git clone --depth 1 git@github.com:mozilla/gecko-dev.git
cd gecko-dev
echo "" > modules/libpref/init/static_prefs/src/lib.rs
cargo dephell -o analysis_results.html
```

The third step neuters the static_prefs crate, which depends on some build-time shenanigans [1], and allows you to reach the relevant error without needing to set your environment up for an actual Firefox build.

[1] https://searchfox.org/mozilla-central/rev/9bf82ef9c097ee6af0e34a1d21c073b2616cc438/modules/libpref/init/static_prefs/src/lib.rs#13

**Comment by mimoo** [comment]
thanks! I'll take a look at it. Note that I'm assuming Firefox is a huge repo, and dephell builds the repo with a simple `cargo build` as part of the analysis: https://github.com/mimoo/cargo-dephell/blob/master/src/analysis.rs#L243 so this might be an issue

**Comment by bholley** [comment]
Oh I see — same problem reproduces just running `cargo build` from the top source directory. I guess the Firefox build system requires some special magic to invoke cargo with the right settings.

I'll just try hacking around it and see how far I get.

**Comment by mimoo** [comment]
looks like Firefox uses its own build thing, which is bad news. But we could add an option to disable the build and lose some functionalities, I think we only use it for unsafe code atm.
